site: sevenbitscience
title: Seven Bit science
description: just a simple personal blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
data-theme: dark # default theme "dark" | "light"

author:
  name: Joey Milausnic
  bio: idk i do stuff or whatever
  username: sevenbitscience # general username
  github: sevenbitscience # github username
  email: milausnic@email.com # email adress

# URL settings
url: "https://sevenbitscience.github.io/" #
baseurl: "" # leave blank if not wishd
permalink: "https://sevenbitscience.github.io/"
# permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

paginate: 5
paginate_path: "/page=:num"
