# Setup
title: Dark Poole
url: https://www.sevenbitscience.com
paginate: 1
paginate_path: "page:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-ZLTQHBSGL2

# Specify the author for blog posts
author:
  name: Joey Milausnic

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: archive

  - title: About
    url: about
